// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel Advance
#pragma kernel VerticalFFT
#pragma kernel HorizontalFFT
#pragma kernel FFTMain

// Textures to hold spectrum and slope data
Texture2D<float4> _InitialSpectrum;
RWTexture2D<float4> _DisplacementSpectrumInput;
RWTexture2D<float4> _DisplacementSpectrumOutput;
RWTexture2D<float4> _SlopeSpectrumInput;
RWTexture2D<float4> _SlopeSpectrumOutput;

// Displacement and slope textures that will be written to
RWTexture2D<float4> _DisplacementTexture;
RWTexture2D<float4> _SlopeTexture;

// Wave parameters
float _MeshResolution;
float _MeshSize;
float _RepeatTime;

float _Time;

// Constants
float PI = 3.1415926536f;
float G = 9.81f;

// Shared memory for FFT calculations
Texture2D<float4> _Butterfly;
uint _Stage;
groupshared float4 sharedDisplacement[512];
groupshared float4 sharedSlope[512];

// The code below is adapted from George Bolba's implemetation of Jerry Tessendorf's Simulating Water paper
float2 ComplexMult(float2 a, float2 b) { return float2(a.x * b.x - a.y * b.y, a.x * b.y + a.y * b.x); }

float2 EulerFormula(float x) { return float2(cos(x), sin(x)); }

// Propagate the waves through time to obtain the displacement spectrum and calculate the slope as well
[numthreads(8, 8, 1)]
void Advance(uint3 id: SV_DispatchThreadID)
{	
    uint2 threadID = id.xy;
	float4 initialSignal = _InitialSpectrum[threadID];

    // Obtain the initial height field (h0) and its complex conjugate (h0conj) from the initial spectrum
    float2 h0 = initialSignal.rg;
    float2 h0conj = initialSignal.ba;
    
    float halfN = _MeshResolution / 2.0f;
    float2 K = (threadID - halfN) * 2.0f * PI / _MeshSize;
    float kMag = length(K);
    float kMagRcp = rcp(kMag);

    if (kMag < 0.0001f) 
    {
        kMagRcp = 1.0f;
    }

    float w_0 = 2.0f * PI / _RepeatTime;
    float dispersion = floor(sqrt(G * kMag) / w_0) * w_0 * _Time;

    float2 exponent = EulerFormula(dispersion);

    float2 htilde = ComplexMult(h0, exponent) + ComplexMult(h0conj, float2(exponent.x, -exponent.y));
    float2 ih = float2(-htilde.y, htilde.x);

	// Derivatives
    float2 displacementX = ih * K.x * kMagRcp;
    float2 displacementY = htilde;
    float2 displacementZ = ih * K.y * kMagRcp;
    float2 displacementX_dx = -htilde * K.x * K.x * kMagRcp;
    float2 displacementY_dx = ih * K.x;
    float2 displacementZ_dx = -htilde * K.x * K.y * kMagRcp;
    float2 displacementY_dz = ih * K.y;
    float2 displacementZ_dz = -htilde * K.y * K.y * kMagRcp;

    float2 htildeDisplacementX = float2(displacementX.x - displacementZ.y, displacementX.y + displacementZ.x);
    float2 htildeDisplacementZ = float2(displacementY.x - displacementZ_dx.y, displacementY.y + displacementZ_dx.x);
        
    float2 htildeSlopeX = float2(displacementY_dx.x - displacementY_dz.y, displacementY_dx.y + displacementY_dz.x);
    float2 htildeSlopeZ = float2(displacementX_dx.x - displacementZ_dz.y, displacementX_dx.y + displacementZ_dz.x);

    // Store the displacement sepctrum and slope spectrums in textures
    _DisplacementSpectrumInput[threadID] = float4(htildeDisplacementX, htildeDisplacementZ);
    _SlopeSpectrumInput[threadID] = float4(htildeSlopeX, htildeSlopeZ);
}

// Perform the inverse FFT to convert the vertical displacement and slope spectrums into the time domain
[numthreads(512, 1, 1)]
void VerticalFFT(
        uint3 id : SV_DispatchThreadID,
        uint3 groupID : SV_GroupID,
        uint3 groupThreadID : SV_GroupThreadID
    )
{
    uint column = groupID.x;
    uint row = groupThreadID.x;

    // Load one column into shared memory
    sharedDisplacement[row] = _DisplacementSpectrumInput[uint2(column,row)];
    sharedSlope[row] = _SlopeSpectrumInput[uint2(column,row)];

    GroupMemoryBarrierWithGroupSync();

    // Butterfly calculations
    float4 lookup = _Butterfly[uint2(row,_Stage)];

    uint left = (uint)(lookup.r * (_MeshResolution - 1));
    uint right = (uint)(lookup.g * (_MeshResolution - 1));

    float2 W = lookup.ba;

    float4 ADisp = sharedDisplacement[left];
    float4 BDisp = sharedDisplacement[right];

    float4 ASlope = sharedSlope[left];
    float4 BSlope = sharedSlope[right];

    // Get x and z components of displacement and slope
    float2 AxDisp = ADisp.rg;
    float2 AzDisp = ADisp.ba;

    float2 BxDisp = BDisp.rg;
    float2 BzDisp = BDisp.ba;

    float2 AxSlope = ASlope.rg;
    float2 AzSlope = ASlope.ba;

    float2 BxSlope = BSlope.rg;
    float2 BzSlope = BSlope.ba;

    // Compute Tx and Tz for displacement and slope
    float2 TxDisp = ComplexMult(BxDisp,W);
    float2 TzDisp = ComplexMult(BzDisp,W);

    float2 TxSlope = ComplexMult(BxSlope,W);
    float2 TzSlope = ComplexMult(BzSlope,W);

    // Compute the new A values for displacement and slope
    float2 newAxDisp = AxDisp + TxDisp;
    float2 newBxDisp = AxDisp - TxDisp;

    float2 newAzDisp = AzDisp + TzDisp;
    float2 newBzDisp = AzDisp - TzDisp;

    float2 newAxSlope = AxSlope + TxSlope;
    float2 newBxSlope = AxSlope - TxSlope;

    float2 newAzSlope = AzSlope + TzSlope;
    float2 newBzSlope = AzSlope - TzSlope;

    // Store the new values back into shared memory
    if(row == left)
    {
        sharedDisplacement[row] = float4(newAxDisp,newAzDisp);
        sharedSlope[row] = float4(newAxSlope,newAzSlope);
    }
    else
    {
        sharedDisplacement[row] = float4(newBxDisp,newBzDisp);
        sharedSlope[row] = float4(newBxSlope,newBzSlope);
    }
    GroupMemoryBarrierWithGroupSync();

    _DisplacementSpectrumOutput[uint2(column,row)] = sharedDisplacement[row];
    _SlopeSpectrumOutput[uint2(column,row)] = sharedSlope[row];
}

// Perform the inverse FFT to convert the horizontal displacement and slope spectrums into the time domain
[numthreads(512, 1, 1)]
void HorizontalFFT(
        uint3 id : SV_DispatchThreadID,
        uint3 groupID : SV_GroupID,
        uint3 groupThreadID : SV_GroupThreadID
)
{
    uint row = groupID.x;
    uint column = groupThreadID.x;

    // Load one row into shared memory
    sharedDisplacement[column] = _DisplacementSpectrumInput[uint2(column,row)];
    sharedSlope[column] = _SlopeSpectrumInput[uint2(column,row)];

    GroupMemoryBarrierWithGroupSync();

    // Butterfly calculations
    float4 lookup = _Butterfly[uint2(column,_Stage)];

    uint left = (uint)(lookup.r * (_MeshResolution - 1));
    uint right = (uint)(lookup.g * (_MeshResolution - 1));

    float2 W = lookup.ba;

    float4 ADisp = sharedDisplacement[left];
    float4 BDisp = sharedDisplacement[right];

    float4 ASlope = sharedSlope[left];
    float4 BSlope = sharedSlope[right];

    // Get x and z components of displacement and slope
    float2 AxDisp = ADisp.rg;
    float2 AzDisp = ADisp.ba;

    float2 BxDisp = BDisp.rg;
    float2 BzDisp = BDisp.ba;

    float2 AxSlope = ASlope.rg;
    float2 AzSlope = ASlope.ba;

    float2 BxSlope = BSlope.rg;
    float2 BzSlope = BSlope.ba;

    // Compute Tx and Tz for displacement and slope
    float2 TxDisp = ComplexMult(BxDisp,W);
    float2 TzDisp = ComplexMult(BzDisp,W);

    float2 TxSlope = ComplexMult(BxSlope,W);
    float2 TzSlope = ComplexMult(BzSlope,W);

    // Compute the new A values for displacement and slope
    float2 newAxDisp = AxDisp + TxDisp;
    float2 newBxDisp = AxDisp - TxDisp;

    float2 newAzDisp = AzDisp + TzDisp;
    float2 newBzDisp = AzDisp - TzDisp;

    float2 newAxSlope = AxSlope + TxSlope;
    float2 newBxSlope = AxSlope - TxSlope;

    float2 newAzSlope = AzSlope + TzSlope;
    float2 newBzSlope = AzSlope - TzSlope;

    // Store the new values back into shared memory
    if(column == left)
    {
        sharedDisplacement[column] = float4(newAxDisp,newAzDisp);
        sharedSlope[column] = float4(newAxSlope,newAzSlope);
    }
    else
    {
        sharedDisplacement[column] = float4(newBxDisp,newBzDisp);
        sharedSlope[column] = float4(newBxSlope,newBzSlope);
    }
    GroupMemoryBarrierWithGroupSync();
  
    _DisplacementSpectrumOutput[uint2(column,row)] = sharedDisplacement[column];
    _SlopeSpectrumOutput[uint2(column,row)] = sharedSlope[column];
}

float4 Permute(float4 data, uint3 id) 
{
    return data * (1.0f - 2.0f * ((id.x + id.y) % 2));
}

// Apply a checkerboard pattern transformation to the spectrums and generate the final displacement and slope maps
[numthreads(8, 8, 1)]
void FFTMain(uint3 id: SV_DispatchThreadID)
{    
    uint2 threadID = id.xy;
    const float2 Lambda = float2(1.0f, 1.0f);

	float4 htildeDisplacement = Permute(_DisplacementSpectrumInput[threadID], id);
	float4 htildeSlope = Permute(_SlopeSpectrumInput[threadID], id);
	
	float2 dxdz = htildeDisplacement.rg;
	float2 dydxz = htildeDisplacement.ba;
	float2 dyxdyz = htildeSlope.rg;
	float2 dxxdzz = htildeSlope.ba;
	
    // float normalization = 1.0f / (_MeshResolution * _MeshResolution);
    float normalization = 1.0f;

	float3 displacement = float3(Lambda.x * dxdz.x, dydxz.x, Lambda.y * dxdz.y) * normalization;
	float2 slopes = dyxdyz.xy / (1 + abs(dxxdzz * Lambda)) * normalization;
	
	_DisplacementTexture[threadID] = float4(displacement, 1.0f);
	_SlopeTexture[threadID] = float4(slopes, 0.0f, 1.0f);
}
