// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel GerstnerMain
#pragma kernel CS_ExtractOceanPatch

// Wave structure to hold wave parameters
struct Wave
{
    float amplitude;
    float wavelength;
    float steepness;
    float2 direction;
    float omega;
    float waveNumber;
};

// Buffers to hold wave data and vertex positions
StructuredBuffer<Wave> _Waves;

// General buffers
StructuredBuffer<float3> _OriginalVertices;
RWStructuredBuffer<float3> _DisplacedVertices;
RWStructuredBuffer<float3> _Normals;

// Wave parameters
int _WaveCount;
float _Time;

float3 EvaluateGerstner(float3 position)
{
    float3 displacement = float3(0,0,0);

    for(int i = 0; i < _WaveCount; i++)
    {
        Wave wave = _Waves[i];

        float phase =
            wave.waveNumber * dot(wave.direction, position.xz)
            - wave.omega * _Time;

        displacement.x +=
            wave.steepness *
            wave.amplitude *
            wave.direction.x *
            cos(phase);

        displacement.y +=
            wave.amplitude *
            sin(phase);

        displacement.z +=
            wave.steepness *
            wave.amplitude *
            wave.direction.y *
            cos(phase);
    }

    return displacement;
}

float3 CalculateNormal(float3 position)
{
    float3 tangentX = float3(1.0, 0.0, 0.0);
    float3 tangentZ = float3(0.0, 0.0, 1.0);

    for (int i = 0; i < _WaveCount; i++)
    {
        Wave wave = _Waves[i];

        float phase = wave.waveNumber * dot(wave.direction, position.xz) - wave.omega * _Time;

        float sinPhase = sin(phase);
        float cosPhase = cos(phase);

        float A = wave.amplitude;
        float k = wave.waveNumber;
        float Q = wave.steepness;

        float Dx = wave.direction.x;
        float Dz = wave.direction.y;

        float common = Q * A * k * sinPhase;

        // Derivative with respect to x
        tangentX += float3(
            -common * Dx * Dx,
             A * k * Dx * cosPhase,
            -common * Dx * Dz
        );

        // Derivative with respect to z
        tangentZ += float3(
            -common * Dx * Dz,
             A * k * Dz * cosPhase,
            -common * Dz * Dz
        );
    }

    return normalize(cross(tangentZ, tangentX));
}

[numthreads(64,1,1)]
void GerstnerMain (uint3 id : SV_DispatchThreadID)
{
    uint index = id.x;

    float3 originalVertex = _OriginalVertices[index];

    float3 displacement = EvaluateGerstner(originalVertex);
    float3 displacedVertex = originalVertex + displacement;

    _DisplacedVertices[index] = displacedVertex;
    _Normals[index] = CalculateNormal(originalVertex);
}

// Buoyancy sample texture
struct OceanSample
{
    float height;
    float3 normal;
};

RWStructuredBuffer<OceanSample> _OceanSamples;
float3 _PatchCentre;
uint _PatchResolution;
float _PatchSize;
uint _N;
float _MeshSize;

[numthreads(8,8,1)]
void CS_ExtractOceanPatch(uint3 id : SV_DISPATCHTHREADID)
{
    if (id.x >= _PatchResolution ||
        id.y >= _PatchResolution)
        return;

    // Get the local patch UV from (0,0) to (1,1)
    float2 uv = (id.xy + 0.5) / _PatchResolution;

    // Convert patch UV into world position
    float2 worldXZ = _PatchCentre.xz + (uv - 0.5) * _PatchSize;

    // Convert world position to ocean texture coordinates
    float2 oceanUV = worldXZ / _MeshSize;

    // Convert UV into integer vertex coordinates
    uint2 vertexCoord = uint2(
        clamp(oceanUV.x * (_N - 1), 0.0f, float(_N - 1)),
        clamp(oceanUV.y * (_N - 1), 0.0f, float(_N - 1))
    );

     // Convert 2D coordinate into a 1D buffer index
    uint vertexIndex = vertexCoord.y * _N + vertexCoord.x;

    // Get the displacement and normal values
    float3 displacement = _DisplacedVertices[vertexIndex];
    float3 normal = _Normals[vertexIndex];

    OceanSample sample;

    sample.height = displacement.y;
    sample.normal = normal;

    _OceanSamples[id.y * _PatchResolution + id.x] = sample;
}
