// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel GerstnerMain

// Wave structure to hold wave parameters
struct Wave
{
    float amplitude;
    float wavelength;
    float steepness;
    float2 direction;
    float omega;
    float waveNumber;
};

// Buffers to hold wave data and vertex positions
StructuredBuffer<Wave> _Waves;

// General buffers
StructuredBuffer<float3> _OriginalVertices;
RWStructuredBuffer<float3> _DisplacedVertices;
RWStructuredBuffer<float3> _Normals;

// Wave parameters
int _WaveCount;
float _Time;

float3 EvaluateGerstner(float3 position)
{
    float3 displacement = float3(0,0,0);

    for(int i = 0; i < _WaveCount; i++)
    {
        Wave wave = _Waves[i];

        float phase =
            wave.waveNumber * dot(wave.direction, position.xz)
            - wave.omega * _Time;

        displacement.x +=
            wave.steepness *
            wave.amplitude *
            wave.direction.x *
            cos(phase);

        displacement.y +=
            wave.amplitude *
            sin(phase);

        displacement.z +=
            wave.steepness *
            wave.amplitude *
            wave.direction.y *
            cos(phase);
    }

    return displacement;
}

float3 CalculateNormal(float3 position)
{
    float3 tangentX = float3(1.0, 0.0, 0.0);
    float3 tangentZ = float3(0.0, 0.0, 1.0);

    for (int i = 0; i < _WaveCount; i++)
    {
        Wave wave = _Waves[i];

        float phase = wave.waveNumber * dot(wave.direction, position.xz) - wave.omega * _Time;

        float sinPhase = sin(phase);
        float cosPhase = cos(phase);

        float A = wave.amplitude;
        float k = wave.waveNumber;
        float Q = wave.steepness;

        float Dx = wave.direction.x;
        float Dz = wave.direction.y;

        float common = Q * A * k * sinPhase;

        // Derivative with respect to x
        tangentX += float3(
            -common * Dx * Dx,
             A * k * Dx * cosPhase,
            -common * Dx * Dz
        );

        // Derivative with respect to z
        tangentZ += float3(
            -common * Dx * Dz,
             A * k * Dz * cosPhase,
            -common * Dz * Dz
        );
    }

    return normalize(cross(tangentZ, tangentX));
}

[numthreads(64,1,1)]
void GerstnerMain (uint3 id : SV_DispatchThreadID)
{
    uint index = id.x;

    float3 originalVertex = _OriginalVertices[index];

    float3 displacement = EvaluateGerstner(originalVertex);
    float3 displacedVertex = originalVertex + displacement;

    _DisplacedVertices[index] = displacedVertex;
    _Normals[index] = CalculateNormal(originalVertex);
}
